export const event = {
  name: "M&N wedding",
  location: "Belgrade, Serbia",
  date: new Date(),
};

export const events = [
  {
    id: 1,
    name: "Next.js Conf",
    location: "San Francisco",
    image: "/images/1.webp",
    date: new Date(),
  },
  {
    id: 2,
    name: "Remix",
    location: "Pars, France",
    image: "/images/2.webp",
    date: new Date(),
  },
  {
    id: 3,
    name: "Party Max",
    location: "Berlin, Germany",
    image: "/images/3.webp",
    date: new Date(),
  },
  {
    id: 4,
    name: "Techno Paradise",
    location: "Istanbul, Turkey",
    image: "/images/4.webp",
    date: new Date(),
  },
  {
    id: 5,
    name: "Nice Nice",
    location: "Belgrade, Serbia",
    image: "/images/5.webp",
    date: new Date(),
  },
  {
    id: 6,
    name: "Hot Mess",
    location: "Belgrade, Serbia",
    image: "/images/2.webp",
    date: new Date(),
  },
  {
    id: 7,
    name: "FreeStyler",
    location: "Belgrade, Serbia",
    image: "/images/3.webp",
    date: new Date(),
  },
  {
    id: 8,
    name: "M&N wedding",
    location: "Belgrade, Serbia",
    image: "/images/5.webp",
    date: new Date(),
  },
];

export const images = [
  { id: 1, src: "/images/1.webp" },
  { id: 2, src: "/images/2.webp" },
  { id: 3, src: "/images/3.webp" },
  { id: 4, src: "/images/4.webp" },
  { id: 5, src: "/images/5.webp" },
  { id: 6, src: "/images/1.webp" },
  { id: 7, src: "/images/2.webp" },
  { id: 8, src: "/images/3.webp" },
  { id: 9, src: "/images/4.webp" },
  { id: 10, src: "/images/5.webp" },
  { id: 11, src: "/images/1.webp" },
  { id: 12, src: "/images/2.webp" },
  { id: 13, src: "/images/3.webp" },
  { id: 14, src: "/images/4.webp" },
  { id: 15, src: "/images/5.webp" },
  { id: 16, src: "/images/1.webp" },
  { id: 17, src: "/images/2.webp" },
  { id: 18, src: "/images/3.webp" },
  { id: 19, src: "/images/4.webp" },
  { id: 20, src: "/images/5.webp" },
];
