export const timezones = [
  {
    id: 0,
    label: "Pacific Time - Los Angeles",
    value: "GMT-07:00",
    city: "Los Angeles",
  },
  {
    id: 1,
    label: "Central Time - Chicago",
    value: "GMT-05:00",
    city: "Chicago",
  },
  {
    id: 2,
    label: "Eastern Time - Toronto",
    value: "GMT-04:00",
    city: "Toronto",
  },
  {
    id: 3,
    label: "Eastern Time - New York",
    value: "GMT-04:00",
    city: "New York",
  },
  {
    id: 4,
    label: "Brasilia Standard Time - Sao Paulo",
    value: "GMT-03:00",
    city: "Sao Paulo",
  },
  {
    id: 5,
    label: "United Kingdom Time - London",
    value: "GMT+00:00",
    city: "London",
  },
  {
    id: 6,
    label: "Central European Time - Brussels",
    value: "GMT+01:00",
    city: "Brussels",
  },
  {
    id: 7,
    label: "Central European Time - Madrid",
    value: "GMT+01:00",
    city: "Madrid",
  },
  {
    id: 8,
    label: "Central European Time - Paris",
    value: "GMT+01:00",
    city: "Paris",
  },
  {
    id: 9,
    label: "Gulf Standard Time - Dubai",
    value: "GMT+04:00",
    city: "Dubai",
  },
  {
    id: 10,
    label: "India Standard Time - Kolkata",
    value: "GMT+05:30",
    city: "Kolkata",
  },
  {
    id: 11,
    label: "Singapore Standard Time - Singapore",
    value: "GMT+08:00",
    city: "Singapore",
  },
  {
    id: 12,
    label: "Japan Standard Time - Tokyo",
    value: "GMT+09:00",
    city: "Tokyo",
  },
  {
    id: 13,
    label: "Niue Time - Niue",
    value: "GMT-11:00",
    city: "Niue",
  },
  {
    id: 14,
    label: "Samoa Standard Time - Pago Pago",
    value: "GMT-11:00",
    city: "Pago Pago",
  },
  {
    id: 15,
    label: "Hawaii-Aleutian Standard Time - Honolulu",
    value: "GMT-10:00",
    city: "Aleutian Standard Time",
  },
  {
    id: 16,
    label: "Cook Islands Standard Time - Rarotonga",
    value: "GMT-10:00",
    city: "Rarotonga",
  },
  {
    id: 17,
    label: "Tahiti Time - Tahiti",
    value: "GMT-10:00",
    city: "Tahiti",
  },
  {
    id: 18,
    label: "Marquesas Time - Marquesas",
    value: "GMT-09:30",
    city: "Marquesas",
  },
  {
    id: 19,
    label: "Hawaii-Aleutian Time (Adak) - Adak",
    value: "GMT-09:00",
    city: "Aleutian Time (Adak)",
  },
  {
    id: 20,
    label: "Gambier Time - Gambier",
    value: "GMT-09:00",
    city: "Gambier",
  },
  {
    id: 21,
    label: "Alaska Time - Anchorage",
    value: "GMT-08:00",
    city: "Anchorage",
  },
  {
    id: 22,
    label: "Alaska Time - Juneau",
    value: "GMT-08:00",
    city: "Juneau",
  },
  {
    id: 23,
    label: "Alaska Time - Metlakatla",
    value: "GMT-08:00",
    city: "Metlakatla",
  },
  {
    id: 24,
    label: "Alaska Time - Nome",
    value: "GMT-08:00",
    city: "Nome",
  },
  {
    id: 25,
    label: "Alaska Time - Sitka",
    value: "GMT-08:00",
    city: "Sitka",
  },
  {
    id: 26,
    label: "Alaska Time - Yakutat",
    value: "GMT-08:00",
    city: "Yakutat",
  },
  {
    id: 27,
    label: "Pitcairn Time - Pitcairn",
    value: "GMT-08:00",
    city: "Pitcairn",
  },
  {
    id: 28,
    label: "Yukon Time - Dawson",
    value: "GMT-07:00",
    city: "Dawson",
  },
  {
    id: 29,
    label: "Mountain Standard Time - Dawson Creek",
    value: "GMT-07:00",
    city: "Dawson Creek",
  },
  {
    id: 30,
    label: "Mountain Standard Time - Fort Nelson",
    value: "GMT-07:00",
    city: "Fort Nelson",
  },
  {
    id: 31,
    label: "Mexican Pacific Standard Time - Hermosillo",
    value: "GMT-07:00",
    city: "Hermosillo",
  },
  {
    id: 32,
    label: "Pacific Time - Los Angeles",
    value: "GMT-07:00",
    city: "Los Angeles",
  },
  {
    id: 33,
    label: "Mexican Pacific Standard Time - Mazatlan",
    value: "GMT-07:00",
    city: "Mazatlan",
  },
  {
    id: 34,
    label: "Mountain Standard Time - Phoenix",
    value: "GMT-07:00",
    city: "Phoenix",
  },
  {
    id: 35,
    label: "Pacific Time - Tijuana",
    value: "GMT-07:00",
    city: "Tijuana",
  },
  {
    id: 36,
    label: "Pacific Time - Vancouver",
    value: "GMT-07:00",
    city: "Vancouver",
  },
  {
    id: 37,
    label: "Yukon Time - Whitehorse",
    value: "GMT-07:00",
    city: "Whitehorse",
  },
  {
    id: 38,
    label: "Central Standard Time - Bahia Banderas",
    value: "GMT-06:00",
    city: "Bahia Banderas",
  },
  {
    id: 39,
    label: "Central Standard Time - Belize",
    value: "GMT-06:00",
    city: "Belize",
  },
  {
    id: 40,
    label: "Mountain Time - Boise",
    value: "GMT-06:00",
    city: "Boise",
  },
  {
    id: 41,
    label: "Mountain Time - Cambridge Bay",
    value: "GMT-06:00",
    city: "Cambridge Bay",
  },
  {
    id: 42,
    label: "Central Standard Time - Chihuahua",
    value: "GMT-06:00",
    city: "Chihuahua",
  },
  {
    id: 43,
    label: "Central Standard Time - Costa Rica",
    value: "GMT-06:00",
    city: "Costa Rica",
  },
  {
    id: 44,
    label: "Mountain Time - Denver",
    value: "GMT-06:00",
    city: "Denver",
  },
  {
    id: 45,
    label: "Mountain Time - Edmonton",
    value: "GMT-06:00",
    city: "Edmonton",
  },
  {
    id: 46,
    label: "Central Standard Time - El Salvador",
    value: "GMT-06:00",
    city: "El Salvador",
  },
  {
    id: 47,
    label: "Central Standard Time - Guatemala",
    value: "GMT-06:00",
    city: "Guatemala",
  },
  {
    id: 48,
    label: "Mountain Time - Inuvik",
    value: "GMT-06:00",
    city: "Inuvik",
  },
  {
    id: 49,
    label: "Central Standard Time - Managua",
    value: "GMT-06:00",
    city: "Managua",
  },
  {
    id: 50,
    label: "Central Standard Time - Merida",
    value: "GMT-06:00",
    city: "Merida",
  },
  {
    id: 51,
    label: "Central Standard Time - Mexico City",
    value: "GMT-06:00",
    city: "Mexico City",
  },
  {
    id: 52,
    label: "Central Standard Time - Monterrey",
    value: "GMT-06:00",
    city: "Monterrey",
  },
  {
    id: 53,
    label: "Central Standard Time - Regina",
    value: "GMT-06:00",
    city: "Regina",
  },
  {
    id: 54,
    label: "Central Standard Time - Swift Current",
    value: "GMT-06:00",
    city: "Swift Current",
  },
  {
    id: 55,
    label: "Central Standard Time - Tegucigalpa",
    value: "GMT-06:00",
    city: "Tegucigalpa",
  },
  {
    id: 56,
    label: "Mountain Time - Yellowknife",
    value: "GMT-06:00",
    city: "Yellowknife",
  },
  {
    id: 57,
    label: "Galapagos Time - Galapagos",
    value: "GMT-06:00",
    city: "Galapagos",
  },
  {
    id: 58,
    label: "Colombia Standard Time - Bogota",
    value: "GMT-05:00",
    city: "Bogota",
  },
  {
    id: 59,
    label: "Eastern Standard Time - Cancun",
    value: "GMT-05:00",
    city: "Cancun",
  },
  {
    id: 60,
    label: "Central Time - Chicago",
    value: "GMT-05:00",
    city: "Chicago",
  },
  {
    id: 61,
    label: "Acre Standard Time - Eirunepe",
    value: "GMT-05:00",
    city: "Eirunepe",
  },
  {
    id: 62,
    label: "Ecuador Time - Guayaquil",
    value: "GMT-05:00",
    city: "Guayaquil",
  },
  {
    id: 63,
    label: "Central Time - Knox, Indiana",
    value: "GMT-05:00",
    city: "Knox, Indiana",
  },
  {
    id: 64,
    label: "Central Time - Tell City, Indiana",
    value: "GMT-05:00",
    city: "Tell City, Indiana",
  },
  {
    id: 65,
    label: "Eastern Standard Time - Jamaica",
    value: "GMT-05:00",
    city: "Jamaica",
  },
  {
    id: 66,
    label: "Peru Standard Time - Lima",
    value: "GMT-05:00",
    city: "Lima",
  },
  {
    id: 67,
    label: "Central Time - Matamoros",
    value: "GMT-05:00",
    city: "Matamoros",
  },
  {
    id: 68,
    label: "Central Time - Menominee",
    value: "GMT-05:00",
    city: "Menominee",
  },
  {
    id: 69,
    label: "Central Time - Beulah, North Dakota",
    value: "GMT-05:00",
    city: "Beulah, North Dakota",
  },
  {
    id: 70,
    label: "Central Time - Center, North Dakota",
    value: "GMT-05:00",
    city: "Center, North Dakota",
  },
  {
    id: 71,
    label: "Central Time - New Salem, North Dakota",
    value: "GMT-05:00",
    city: "New Salem, North Dakota",
  },
  {
    id: 72,
    label: "Central Time - Ojinaga",
    value: "GMT-05:00",
    city: "Ojinaga",
  },
  {
    id: 73,
    label: "Eastern Standard Time - Panama",
    value: "GMT-05:00",
    city: "Panama",
  },
  {
    id: 74,
    label: "Central Time - Rainy River",
    value: "GMT-05:00",
    city: "Rainy River",
  },
  {
    id: 75,
    label: "Central Time - Rankin Inlet",
    value: "GMT-05:00",
    city: "Rankin Inlet",
  },
  {
    id: 76,
    label: "Central Time - Resolute",
    value: "GMT-05:00",
    city: "Resolute",
  },
  {
    id: 77,
    label: "Acre Standard Time - Rio Branco",
    value: "GMT-05:00",
    city: "Rio Branco",
  },
  {
    id: 78,
    label: "Central Time - Winnipeg",
    value: "GMT-05:00",
    city: "Winnipeg",
  },
  {
    id: 79,
    label: "Easter Island Time - Easter",
    value: "GMT-05:00",
    city: "Easter",
  },
  {
    id: 80,
    label: "Atlantic Standard Time - Barbados",
    value: "GMT-04:00",
    city: "Barbados",
  },
  {
    id: 81,
    label: "Amazon Standard Time - Boa Vista",
    value: "GMT-04:00",
    city: "Boa Vista",
  },
  {
    id: 82,
    label: "Amazon Standard Time - Campo Grande",
    value: "GMT-04:00",
    city: "Campo Grande",
  },
  {
    id: 83,
    label: "Venezuela Time - Caracas",
    value: "GMT-04:00",
    city: "Caracas",
  },
  {
    id: 84,
    label: "Amazon Standard Time - Cuiaba",
    value: "GMT-04:00",
    city: "Cuiaba",
  },
  {
    id: 85,
    label: "Eastern Time - Detroit",
    value: "GMT-04:00",
    city: "Detroit",
  },
  {
    id: 86,
    label: "Eastern Time - Grand Turk",
    value: "GMT-04:00",
    city: "Grand Turk",
  },
  {
    id: 87,
    label: "Guyana Time - Guyana",
    value: "GMT-04:00",
    city: "Guyana",
  },
  {
    id: 88,
    label: "Cuba Time - Havana",
    value: "GMT-04:00",
    city: "Havana",
  },
  {
    id: 89,
    label: "Eastern Time - Indianapolis, Indiana",
    value: "GMT-04:00",
    city: "Indianapolis, Indiana",
  },
  {
    id: 90,
    label: "Eastern Time - Marengo, Indiana",
    value: "GMT-04:00",
    city: "Marengo, Indiana",
  },
  {
    id: 91,
    label: "Eastern Time - Petersburg, Indiana",
    value: "GMT-04:00",
    city: "Petersburg, Indiana",
  },
  {
    id: 92,
    label: "Eastern Time - Vevay, Indiana",
    value: "GMT-04:00",
    city: "Vevay, Indiana",
  },
  {
    id: 93,
    label: "Eastern Time - Vincennes, Indiana",
    value: "GMT-04:00",
    city: "Vincennes, Indiana",
  },
  {
    id: 94,
    label: "Eastern Time - Winamac, Indiana",
    value: "GMT-04:00",
    city: "Winamac, Indiana",
  },
  {
    id: 95,
    label: "Eastern Time - Iqaluit",
    value: "GMT-04:00",
    city: "Iqaluit",
  },
  {
    id: 96,
    label: "Eastern Time - Louisville, Kentucky",
    value: "GMT-04:00",
    city: "Louisville, Kentucky",
  },
  {
    id: 97,
    label: "Eastern Time - Monticello, Kentucky",
    value: "GMT-04:00",
    city: "Monticello, Kentucky",
  },
  {
    id: 98,
    label: "Bolivia Time - La Paz",
    value: "GMT-04:00",
    city: "La Paz",
  },
  {
    id: 99,
    label: "Amazon Standard Time - Manaus",
    value: "GMT-04:00",
    city: "Manaus",
  },
  {
    id: 100,
    label: "Atlantic Standard Time - Martinique",
    value: "GMT-04:00",
    city: "Martinique",
  },
  {
    id: 101,
    label: "Eastern Time - New York",
    value: "GMT-04:00",
    city: "New York",
  },
  {
    id: 102,
    label: "Eastern Time - Nipigon",
    value: "GMT-04:00",
    city: "Nipigon",
  },
  {
    id: 103,
    label: "Eastern Time - Pangnirtung",
    value: "GMT-04:00",
    city: "Pangnirtung",
  },
  {
    id: 104,
    label: "Eastern Time - Port-au-Prince",
    value: "GMT-04:00",
    city: "Port",
  },
  {
    id: 105,
    label: "Amazon Standard Time - Porto Velho",
    value: "GMT-04:00",
    city: "Porto Velho",
  },
  {
    id: 106,
    label: "Atlantic Standard Time - Puerto Rico",
    value: "GMT-04:00",
    city: "Puerto Rico",
  },
  {
    id: 107,
    label: "Atlantic Standard Time - Santo Domingo",
    value: "GMT-04:00",
    city: "Santo Domingo",
  },
  {
    id: 108,
    label: "Eastern Time - Thunder Bay",
    value: "GMT-04:00",
    city: "Thunder Bay",
  },
  {
    id: 109,
    label: "Eastern Time - Toronto",
    value: "GMT-04:00",
    city: "Toronto",
  },
  {
    id: 110,
    label: "Brasilia Standard Time - Araguaina",
    value: "GMT-03:00",
    city: "Araguaina",
  },
  {
    id: 111,
    label: "Argentina Standard Time - Buenos Aires, Argentina",
    value: "GMT-03:00",
    city: "Buenos Aires, Argentina",
  },
  {
    id: 112,
    label: "Argentina Standard Time - Catamarca, Argentina",
    value: "GMT-03:00",
    city: "Catamarca, Argentina",
  },
  {
    id: 113,
    label: "Argentina Standard Time - Cordoba, Argentina",
    value: "GMT-03:00",
    city: "Cordoba, Argentina",
  },
  {
    id: 114,
    label: "Argentina Standard Time - Jujuy, Argentina",
    value: "GMT-03:00",
    city: "Jujuy, Argentina",
  },
  {
    id: 115,
    label: "Argentina Standard Time - La Rioja, Argentina",
    value: "GMT-03:00",
    city: "La Rioja, Argentina",
  },
  {
    id: 116,
    label: "Argentina Standard Time - Mendoza, Argentina",
    value: "GMT-03:00",
    city: "Mendoza, Argentina",
  },
  {
    id: 117,
    label: "Argentina Standard Time - Rio Gallegos, Argentina",
    value: "GMT-03:00",
    city: "Rio Gallegos, Argentina",
  },
  {
    id: 118,
    label: "Argentina Standard Time - Salta, Argentina",
    value: "GMT-03:00",
    city: "Salta, Argentina",
  },
  {
    id: 119,
    label: "Argentina Standard Time - San Juan, Argentina",
    value: "GMT-03:00",
    city: "San Juan, Argentina",
  },
  {
    id: 120,
    label: "Argentina Standard Time - San Luis, Argentina",
    value: "GMT-03:00",
    city: "San Luis, Argentina",
  },
  {
    id: 121,
    label: "Argentina Standard Time - Tucuman, Argentina",
    value: "GMT-03:00",
    city: "Tucuman, Argentina",
  },
  {
    id: 122,
    label: "Argentina Standard Time - Ushuaia, Argentina",
    value: "GMT-03:00",
    city: "Ushuaia, Argentina",
  },
  {
    id: 123,
    label: "Paraguay Time - Asuncion",
    value: "GMT-03:00",
    city: "Asuncion",
  },
  {
    id: 124,
    label: "Brasilia Standard Time - Bahia",
    value: "GMT-03:00",
    city: "Bahia",
  },
  {
    id: 125,
    label: "Brasilia Standard Time - Belem",
    value: "GMT-03:00",
    city: "Belem",
  },
  {
    id: 126,
    label: "French Guiana Time - Cayenne",
    value: "GMT-03:00",
    city: "Cayenne",
  },
  {
    id: 127,
    label: "Brasilia Standard Time - Fortaleza",
    value: "GMT-03:00",
    city: "Fortaleza",
  },
  {
    id: 128,
    label: "Atlantic Time - Glace Bay",
    value: "GMT-03:00",
    city: "Glace Bay",
  },
  {
    id: 129,
    label: "Atlantic Time - Goose Bay",
    value: "GMT-03:00",
    city: "Goose Bay",
  },
  {
    id: 130,
    label: "Atlantic Time - Halifax",
    value: "GMT-03:00",
    city: "Halifax",
  },
  {
    id: 131,
    label: "Brasilia Standard Time - Maceio",
    value: "GMT-03:00",
    city: "Maceio",
  },
  {
    id: 132,
    label: "Atlantic Time - Moncton",
    value: "GMT-03:00",
    city: "Moncton",
  },
  {
    id: 133,
    label: "Uruguay Standard Time - Montevideo",
    value: "GMT-03:00",
    city: "Montevideo",
  },
  {
    id: 134,
    label: "Suriname Time - Paramaribo",
    value: "GMT-03:00",
    city: "Paramaribo",
  },
  {
    id: 135,
    label: "Punta Arenas Time - Punta Arenas",
    value: "GMT-03:00",
    city: "Punta Arenas",
  },
  {
    id: 136,
    label: "Brasilia Standard Time - Recife",
    value: "GMT-03:00",
    city: "Recife",
  },
  {
    id: 137,
    label: "Brasilia Standard Time - Santarem",
    value: "GMT-03:00",
    city: "Santarem",
  },
  {
    id: 138,
    label: "Chile Time - Santiago",
    value: "GMT-03:00",
    city: "Santiago",
  },
  {
    id: 139,
    label: "Brasilia Standard Time - Sao Paulo",
    value: "GMT-03:00",
    city: "Sao Paulo",
  },
  {
    id: 140,
    label: "Atlantic Time - Thule",
    value: "GMT-03:00",
    city: "Thule",
  },
  {
    id: 141,
    label: "Palmer Time - Palmer",
    value: "GMT-03:00",
    city: "Palmer",
  },
  {
    id: 142,
    label: "Rothera Time - Rothera",
    value: "GMT-03:00",
    city: "Rothera",
  },
  {
    id: 143,
    label: "Atlantic Time - Bermuda",
    value: "GMT-03:00",
    city: "Bermuda",
  },
  {
    id: 144,
    label: "Falkland Islands Standard Time - Stanley",
    value: "GMT-03:00",
    city: "Stanley",
  },
  {
    id: 145,
    label: "Newfoundland Time - St Johns",
    value: "GMT-02:30",
    city: "St Johns",
  },
  {
    id: 146,
    label: "St Pierre & Miquelon Time - Miquelon",
    value: "GMT-02:00",
    city: "Miquelon",
  },
  {
    id: 147,
    label: "Fernando de Noronha Standard Time - Noronha",
    value: "GMT-02:00",
    city: "Noronha",
  },
  {
    id: 148,
    label: "West Greenland Time - Nuuk",
    value: "GMT-02:00",
    city: "Nuuk",
  },
  {
    id: 149,
    label: "South Georgia Time - South Georgia",
    value: "GMT-02:00",
    city: "South Georgia",
  },
  {
    id: 150,
    label: "East Greenland Time - Scoresbysund",
    value: "GMT-01:00",
    city: "Scoresbysund",
  },
  {
    id: 151,
    label: "Azores Time - Azores",
    value: "GMT-01:00",
    city: "Azores",
  },
  {
    id: 152,
    label: "Cape Verde Standard Time - Cape Verde",
    value: "GMT-01:00",
    city: "Cape Verde",
  },
  {
    id: 153,
    label: "Greenwich Mean Time - Abidjan",
    value: "GMT+00:00",
    city: "Abidjan",
  },
  {
    id: 154,
    label: "Greenwich Mean Time - Bissau",
    value: "GMT+00:00",
    city: "Bissau",
  },
  {
    id: 155,
    label: "Morocco Time - Casablanca",
    value: "GMT+00:00",
    city: "Casablanca",
  },
  {
    id: 156,
    label: "Western Sahara Time - El Aaiun",
    value: "GMT+00:00",
    city: "El Aaiun",
  },
  {
    id: 157,
    label: "Greenwich Mean Time - Monrovia",
    value: "GMT+00:00",
    city: "Monrovia",
  },
  {
    id: 158,
    label: "Greenwich Mean Time - Sao Tome",
    value: "GMT+00:00",
    city: "Sao Tome",
  },
  {
    id: 159,
    label: "Greenwich Mean Time - Danmarkshavn",
    value: "GMT+00:00",
    city: "Danmarkshavn",
  },
  {
    id: 160,
    label: "Troll Time - Troll",
    value: "GMT+00:00",
    city: "Troll",
  },
  {
    id: 161,
    label: "Western European Time - Canary",
    value: "GMT+00:00",
    city: "Canary",
  },
  {
    id: 162,
    label: "Western European Time - Faroe",
    value: "GMT+00:00",
    city: "Faroe",
  },
  {
    id: 163,
    label: "Western European Time - Madeira",
    value: "GMT+00:00",
    city: "Madeira",
  },
  {
    id: 164,
    label: "Greenwich Mean Time - Reykjavik",
    value: "GMT+00:00",
    city: "Reykjavik",
  },
  {
    id: 165,
    label: "Ireland Time - Dublin",
    value: "GMT+00:00",
    city: "Dublin",
  },
  {
    id: 166,
    label: "Western European Time - Lisbon",
    value: "GMT+00:00",
    city: "Lisbon",
  },
  {
    id: 167,
    label: "United Kingdom Time - London",
    value: "GMT+00:00",
    city: "London",
  },
  {
    id: 168,
    label: "UTC - UTC",
    value: "GMT+00:00",
    city: "UTC",
  },
  {
    id: 169,
    label: "Central European Standard Time - Algiers",
    value: "GMT+01:00",
    city: "Algiers",
  },
  {
    id: 170,
    label: "Central European Time - Ceuta",
    value: "GMT+01:00",
    city: "Ceuta",
  },
  {
    id: 171,
    label: "West Africa Standard Time - Lagos",
    value: "GMT+01:00",
    city: "Lagos",
  },
  {
    id: 172,
    label: "West Africa Standard Time - Ndjamena",
    value: "GMT+01:00",
    city: "Ndjamena",
  },
  {
    id: 173,
    label: "Central European Standard Time - Tunis",
    value: "GMT+01:00",
    city: "Tunis",
  },
  {
    id: 174,
    label: "Central European Time - Amsterdam",
    value: "GMT+01:00",
    city: "Amsterdam",
  },
  {
    id: 175,
    label: "Central European Time - Andorra",
    value: "GMT+01:00",
    city: "Andorra",
  },
  {
    id: 176,
    label: "Central European Time - Belgrade",
    value: "GMT+01:00",
    city: "Belgrade",
  },
  {
    id: 177,
    label: "Central European Time - Berlin",
    value: "GMT+01:00",
    city: "Berlin",
  },
  {
    id: 178,
    label: "Central European Time - Brussels",
    value: "GMT+01:00",
    city: "Brussels",
  },
  {
    id: 179,
    label: "Central European Time - Budapest",
    value: "GMT+01:00",
    city: "Budapest",
  },
  {
    id: 180,
    label: "Central European Time - Copenhagen",
    value: "GMT+01:00",
    city: "Copenhagen",
  },
  {
    id: 181,
    label: "Central European Time - Gibraltar",
    value: "GMT+01:00",
    city: "Gibraltar",
  },
  {
    id: 182,
    label: "Central European Time - Luxembourg",
    value: "GMT+01:00",
    city: "Luxembourg",
  },
  {
    id: 183,
    label: "Central European Time - Madrid",
    value: "GMT+01:00",
    city: "Madrid",
  },
  {
    id: 184,
    label: "Central European Time - Malta",
    value: "GMT+01:00",
    city: "Malta",
  },
  {
    id: 185,
    label: "Central European Time - Monaco",
    value: "GMT+01:00",
    city: "Monaco",
  },
  {
    id: 186,
    label: "Central European Time - Oslo",
    value: "GMT+01:00",
    city: "Oslo",
  },
  {
    id: 187,
    label: "Central European Time - Paris",
    value: "GMT+01:00",
    city: "Paris",
  },
  {
    id: 188,
    label: "Central European Time - Prague",
    value: "GMT+01:00",
    city: "Prague",
  },
  {
    id: 189,
    label: "Central European Time - Rome",
    value: "GMT+01:00",
    city: "Rome",
  },
  {
    id: 190,
    label: "Central European Time - Stockholm",
    value: "GMT+01:00",
    city: "Stockholm",
  },
  {
    id: 191,
    label: "Central European Time - Tirane",
    value: "GMT+01:00",
    city: "Tirane",
  },
  {
    id: 192,
    label: "Central European Time - Vienna",
    value: "GMT+01:00",
    city: "Vienna",
  },
  {
    id: 193,
    label: "Central European Time - Warsaw",
    value: "GMT+01:00",
    city: "Warsaw",
  },
  {
    id: 194,
    label: "Central European Time - Zurich",
    value: "GMT+01:00",
    city: "Zurich",
  },
  {
    id: 195,
    label: "Eastern European Time - Cairo",
    value: "GMT+02:00",
    city: "Cairo",
  },
  {
    id: 196,
    label: "South Africa Standard Time - Johannesburg",
    value: "GMT+02:00",
    city: "Johannesburg",
  },
  {
    id: 197,
    label: "Central Africa Time - Juba",
    value: "GMT+02:00",
    city: "Juba",
  },
  {
    id: 198,
    label: "Central Africa Time - Khartoum",
    value: "GMT+02:00",
    city: "Khartoum",
  },
  {
    id: 199,
    label: "Central Africa Time - Maputo",
    value: "GMT+02:00",
    city: "Maputo",
  },
  {
    id: 200,
    label: "Eastern European Standard Time - Tripoli",
    value: "GMT+02:00",
    city: "Tripoli",
  },
  {
    id: 201,
    label: "Central Africa Time - Windhoek",
    value: "GMT+02:00",
    city: "Windhoek",
  },
  {
    id: 202,
    label: "Eastern European Time - Beirut",
    value: "GMT+02:00",
    city: "Beirut",
  },
  {
    id: 203,
    label: "Famagusta Time - Famagusta",
    value: "GMT+02:00",
    city: "Famagusta",
  },
  {
    id: 204,
    label: "Eastern European Time - Gaza",
    value: "GMT+02:00",
    city: "Gaza",
  },
  {
    id: 205,
    label: "Eastern European Time - Hebron",
    value: "GMT+02:00",
    city: "Hebron",
  },
  {
    id: 206,
    label: "Israel Time - Jerusalem",
    value: "GMT+02:00",
    city: "Jerusalem",
  },
  {
    id: 207,
    label: "Eastern European Time - Nicosia",
    value: "GMT+02:00",
    city: "Nicosia",
  },
  {
    id: 208,
    label: "Eastern European Time - Athens",
    value: "GMT+02:00",
    city: "Athens",
  },
  {
    id: 209,
    label: "Eastern European Time - Bucharest",
    value: "GMT+02:00",
    city: "Bucharest",
  },
  {
    id: 210,
    label: "Eastern European Time - Chisinau",
    value: "GMT+02:00",
    city: "Chisinau",
  },
  {
    id: 211,
    label: "Eastern European Time - Helsinki",
    value: "GMT+02:00",
    city: "Helsinki",
  },
  {
    id: 212,
    label: "Eastern European Standard Time - Kaliningrad",
    value: "GMT+02:00",
    city: "Kaliningrad",
  },
  {
    id: 213,
    label: "Eastern European Time - Kiev",
    value: "GMT+02:00",
    city: "Kiev",
  },
  {
    id: 214,
    label: "Eastern European Time - Riga",
    value: "GMT+02:00",
    city: "Riga",
  },
  {
    id: 215,
    label: "Eastern European Time - Sofia",
    value: "GMT+02:00",
    city: "Sofia",
  },
  {
    id: 216,
    label: "Eastern European Time - Tallinn",
    value: "GMT+02:00",
    city: "Tallinn",
  },
  {
    id: 217,
    label: "Eastern European Time - Uzhgorod",
    value: "GMT+02:00",
    city: "Uzhgorod",
  },
  {
    id: 218,
    label: "Eastern European Time - Vilnius",
    value: "GMT+02:00",
    city: "Vilnius",
  },
  {
    id: 219,
    label: "Eastern European Time - Zaporozhye",
    value: "GMT+02:00",
    city: "Zaporozhye",
  },
  {
    id: 220,
    label: "East Africa Time - Nairobi",
    value: "GMT+03:00",
    city: "Nairobi",
  },
  {
    id: 221,
    label: "Jordan Time - Amman",
    value: "GMT+03:00",
    city: "Amman",
  },
  {
    id: 222,
    label: "Arabian Standard Time - Baghdad",
    value: "GMT+03:00",
    city: "Baghdad",
  },
  {
    id: 223,
    label: "Syria Time - Damascus",
    value: "GMT+03:00",
    city: "Damascus",
  },
  {
    id: 224,
    label: "Arabian Standard Time - Qatar",
    value: "GMT+03:00",
    city: "Qatar",
  },
  {
    id: 225,
    label: "Arabian Standard Time - Riyadh",
    value: "GMT+03:00",
    city: "Riyadh",
  },
  {
    id: 226,
    label: "Türkiye Time - Istanbul",
    value: "GMT+03:00",
    city: "Istanbul",
  },
  {
    id: 227,
    label: "Kirov Time - Kirov",
    value: "GMT+03:00",
    city: "Kirov",
  },
  {
    id: 228,
    label: "Moscow Standard Time - Minsk",
    value: "GMT+03:00",
    city: "Minsk",
  },
  {
    id: 229,
    label: "Moscow Standard Time - Moscow",
    value: "GMT+03:00",
    city: "Moscow",
  },
  {
    id: 230,
    label: "Moscow Standard Time - Simferopol",
    value: "GMT+03:00",
    city: "Simferopol",
  },
  {
    id: 231,
    label: "Volgograd Standard Time - Volgograd",
    value: "GMT+03:00",
    city: "Volgograd",
  },
  {
    id: 232,
    label: "Iran Standard Time - Tehran",
    value: "GMT+03:30",
    city: "Tehran",
  },
  {
    id: 233,
    label: "Azerbaijan Standard Time - Baku",
    value: "GMT+04:00",
    city: "Baku",
  },
  {
    id: 234,
    label: "Gulf Standard Time - Dubai",
    value: "GMT+04:00",
    city: "Dubai",
  },
  {
    id: 235,
    label: "Georgia Standard Time - Tbilisi",
    value: "GMT+04:00",
    city: "Tbilisi",
  },
  {
    id: 236,
    label: "Armenia Standard Time - Yerevan",
    value: "GMT+04:00",
    city: "Yerevan",
  },
  {
    id: 237,
    label: "Astrakhan Time - Astrakhan",
    value: "GMT+04:00",
    city: "Astrakhan",
  },
  {
    id: 238,
    label: "Samara Standard Time - Samara",
    value: "GMT+04:00",
    city: "Samara",
  },
  {
    id: 239,
    label: "Saratov Time - Saratov",
    value: "GMT+04:00",
    city: "Saratov",
  },
  {
    id: 240,
    label: "Ulyanovsk Time - Ulyanovsk",
    value: "GMT+04:00",
    city: "Ulyanovsk",
  },
  {
    id: 241,
    label: "Seychelles Time - Mahe",
    value: "GMT+04:00",
    city: "Mahe",
  },
  {
    id: 242,
    label: "Mauritius Standard Time - Mauritius",
    value: "GMT+04:00",
    city: "Mauritius",
  },
  {
    id: 243,
    label: "Réunion Time - Reunion",
    value: "GMT+04:00",
    city: "Reunion",
  },
  {
    id: 244,
    label: "Afghanistan Time - Kabul",
    value: "GMT+04:30",
    city: "Kabul",
  },
  {
    id: 245,
    label: "Mawson Time - Mawson",
    value: "GMT+05:00",
    city: "Mawson",
  },
  {
    id: 246,
    label: "Vostok Time - Vostok",
    value: "GMT+05:00",
    city: "Vostok",
  },
  {
    id: 247,
    label: "West Kazakhstan Time - Almaty",
    value: "GMT+05:00",
    city: "Almaty",
  },
  {
    id: 248,
    label: "West Kazakhstan Time - Aqtau",
    value: "GMT+05:00",
    city: "Aqtau",
  },
  {
    id: 249,
    label: "West Kazakhstan Time - Aqtobe",
    value: "GMT+05:00",
    city: "Aqtobe",
  },
  {
    id: 250,
    label: "Turkmenistan Standard Time - Ashgabat",
    value: "GMT+05:00",
    city: "Ashgabat",
  },
  {
    id: 251,
    label: "West Kazakhstan Time - Atyrau",
    value: "GMT+05:00",
    city: "Atyrau",
  },
  {
    id: 252,
    label: "Tajikistan Time - Dushanbe",
    value: "GMT+05:00",
    city: "Dushanbe",
  },
  {
    id: 253,
    label: "Pakistan Standard Time - Karachi",
    value: "GMT+05:00",
    city: "Karachi",
  },
  {
    id: 254,
    label: "West Kazakhstan Time - Oral",
    value: "GMT+05:00",
    city: "Oral",
  },
  {
    id: 255,
    label: "West Kazakhstan Time - Qostanay",
    value: "GMT+05:00",
    city: "Qostanay",
  },
  {
    id: 256,
    label: "West Kazakhstan Time - Qyzylorda",
    value: "GMT+05:00",
    city: "Qyzylorda",
  },
  {
    id: 257,
    label: "Uzbekistan Standard Time - Samarkand",
    value: "GMT+05:00",
    city: "Samarkand",
  },
  {
    id: 258,
    label: "Uzbekistan Standard Time - Tashkent",
    value: "GMT+05:00",
    city: "Tashkent",
  },
  {
    id: 259,
    label: "Yekaterinburg Standard Time - Yekaterinburg",
    value: "GMT+05:00",
    city: "Yekaterinburg",
  },
  {
    id: 260,
    label: "French Southern & Antarctic Time - Kerguelen",
    value: "GMT+05:00",
    city: "Kerguelen",
  },
  {
    id: 261,
    label: "Maldives Time - Maldives",
    value: "GMT+05:00",
    city: "Maldives",
  },
  {
    id: 262,
    label: "India Standard Time - Colombo",
    value: "GMT+05:30",
    city: "Colombo",
  },
  {
    id: 263,
    label: "India Standard Time - Kolkata",
    value: "GMT+05:30",
    city: "Kolkata",
  },
  {
    id: 264,
    label: "Nepal Time - Kathmandu",
    value: "GMT+05:45",
    city: "Kathmandu",
  },
  {
    id: 265,
    label: "Kyrgyzstan Time - Bishkek",
    value: "GMT+06:00",
    city: "Bishkek",
  },
  {
    id: 266,
    label: "Bangladesh Standard Time - Dhaka",
    value: "GMT+06:00",
    city: "Dhaka",
  },
  {
    id: 267,
    label: "Omsk Standard Time - Omsk",
    value: "GMT+06:00",
    city: "Omsk",
  },
  {
    id: 268,
    label: "Bhutan Time - Thimphu",
    value: "GMT+06:00",
    city: "Thimphu",
  },
  {
    id: 269,
    label: "Urumqi Time - Urumqi",
    value: "GMT+06:00",
    city: "Urumqi",
  },
  {
    id: 270,
    label: "Indian Ocean Time - Chagos",
    value: "GMT+06:00",
    city: "Chagos",
  },
  {
    id: 271,
    label: "Myanmar Time - Yangon",
    value: "GMT+06:30",
    city: "Yangon",
  },
  {
    id: 272,
    label: "Cocos Islands Time - Cocos",
    value: "GMT+06:30",
    city: "Cocos",
  },
  {
    id: 273,
    label: "Davis Time - Davis",
    value: "GMT+07:00",
    city: "Davis",
  },
  {
    id: 274,
    label: "Indochina Time - Bangkok",
    value: "GMT+07:00",
    city: "Bangkok",
  },
  {
    id: 275,
    label: "Barnaul Time - Barnaul",
    value: "GMT+07:00",
    city: "Barnaul",
  },
  {
    id: 276,
    label: "Indochina Time - Ho Chi Minh",
    value: "GMT+07:00",
    city: "Ho Chi Minh",
  },
  {
    id: 277,
    label: "Hovd Standard Time - Hovd",
    value: "GMT+07:00",
    city: "Hovd",
  },
  {
    id: 278,
    label: "Western Indonesia Time - Jakarta",
    value: "GMT+07:00",
    city: "Jakarta",
  },
  {
    id: 279,
    label: "Krasnoyarsk Standard Time - Krasnoyarsk",
    value: "GMT+07:00",
    city: "Krasnoyarsk",
  },
  {
    id: 280,
    label: "Krasnoyarsk Standard Time - Novokuznetsk",
    value: "GMT+07:00",
    city: "Novokuznetsk",
  },
  {
    id: 281,
    label: "Novosibirsk Standard Time - Novosibirsk",
    value: "GMT+07:00",
    city: "Novosibirsk",
  },
  {
    id: 282,
    label: "Western Indonesia Time - Pontianak",
    value: "GMT+07:00",
    city: "Pontianak",
  },
  {
    id: 283,
    label: "Tomsk Time - Tomsk",
    value: "GMT+07:00",
    city: "Tomsk",
  },
  {
    id: 284,
    label: "Christmas Island Time - Christmas",
    value: "GMT+07:00",
    city: "Christmas",
  },
  {
    id: 285,
    label: "Australian Western Standard Time - Casey",
    value: "GMT+08:00",
    city: "Casey",
  },
  {
    id: 286,
    label: "Brunei Darussalam Time - Brunei",
    value: "GMT+08:00",
    city: "Brunei",
  },
  {
    id: 287,
    label: "Ulaanbaatar Standard Time - Choibalsan",
    value: "GMT+08:00",
    city: "Choibalsan",
  },
  {
    id: 288,
    label: "Hong Kong Standard Time - Hong Kong",
    value: "GMT+08:00",
    city: "Hong Kong",
  },
  {
    id: 289,
    label: "Irkutsk Standard Time - Irkutsk",
    value: "GMT+08:00",
    city: "Irkutsk",
  },
  {
    id: 290,
    label: "Malaysia Time - Kuala Lumpur",
    value: "GMT+08:00",
    city: "Kuala Lumpur",
  },
  {
    id: 291,
    label: "Malaysia Time - Kuching",
    value: "GMT+08:00",
    city: "Kuching",
  },
  {
    id: 292,
    label: "China Standard Time - Macau",
    value: "GMT+08:00",
    city: "Macau",
  },
  {
    id: 293,
    label: "Central Indonesia Time - Makassar",
    value: "GMT+08:00",
    city: "Makassar",
  },
  {
    id: 294,
    label: "Philippine Standard Time - Manila",
    value: "GMT+08:00",
    city: "Manila",
  },
  {
    id: 295,
    label: "China Standard Time - Shanghai",
    value: "GMT+08:00",
    city: "Shanghai",
  },
  {
    id: 296,
    label: "Singapore Standard Time - Singapore",
    value: "GMT+08:00",
    city: "Singapore",
  },
  {
    id: 297,
    label: "Taipei Standard Time - Taipei",
    value: "GMT+08:00",
    city: "Taipei",
  },
  {
    id: 298,
    label: "Ulaanbaatar Standard Time - Ulaanbaatar",
    value: "GMT+08:00",
    city: "Ulaanbaatar",
  },
  {
    id: 299,
    label: "Australian Western Standard Time - Perth",
    value: "GMT+08:00",
    city: "Perth",
  },
  {
    id: 300,
    label: "Australian Central Western Standard Time - Eucla",
    value: "GMT+08:45",
    city: "Eucla",
  },
  {
    id: 301,
    label: "Yakutsk Standard Time - Chita",
    value: "GMT+09:00",
    city: "Chita",
  },
  {
    id: 302,
    label: "East Timor Time - Dili",
    value: "GMT+09:00",
    city: "Dili",
  },
  {
    id: 303,
    label: "Eastern Indonesia Time - Jayapura",
    value: "GMT+09:00",
    city: "Jayapura",
  },
  {
    id: 304,
    label: "Yakutsk Standard Time - Khandyga",
    value: "GMT+09:00",
    city: "Khandyga",
  },
  {
    id: 305,
    label: "Korean Standard Time - Pyongyang",
    value: "GMT+09:00",
    city: "Pyongyang",
  },
  {
    id: 306,
    label: "Korean Standard Time - Seoul",
    value: "GMT+09:00",
    city: "Seoul",
  },
  {
    id: 307,
    label: "Japan Standard Time - Tokyo",
    value: "GMT+09:00",
    city: "Tokyo",
  },
  {
    id: 308,
    label: "Yakutsk Standard Time - Yakutsk",
    value: "GMT+09:00",
    city: "Yakutsk",
  },
  {
    id: 309,
    label: "Palau Time - Palau",
    value: "GMT+09:00",
    city: "Palau",
  },
  {
    id: 310,
    label: "Australian Central Standard Time - Darwin",
    value: "GMT+09:30",
    city: "Darwin",
  },
  {
    id: 311,
    label: "Vladivostok Standard Time - Ust-Nera",
    value: "GMT+10:00",
    city: "Ust",
  },
  {
    id: 312,
    label: "Vladivostok Standard Time - Vladivostok",
    value: "GMT+10:00",
    city: "Vladivostok",
  },
  {
    id: 313,
    label: "Australian Eastern Standard Time - Brisbane",
    value: "GMT+10:00",
    city: "Brisbane",
  },
  {
    id: 314,
    label: "Australian Eastern Standard Time - Lindeman",
    value: "GMT+10:00",
    city: "Lindeman",
  },
  {
    id: 315,
    label: "Chuuk Time - Chuuk",
    value: "GMT+10:00",
    city: "Chuuk",
  },
  {
    id: 316,
    label: "Chamorro Standard Time - Guam",
    value: "GMT+10:00",
    city: "Guam",
  },
  {
    id: 317,
    label: "Papua New Guinea Time - Port Moresby",
    value: "GMT+10:00",
    city: "Port Moresby",
  },
  {
    id: 318,
    label: "Central Australia Time - Adelaide",
    value: "GMT+10:30",
    city: "Adelaide",
  },
  {
    id: 319,
    label: "Central Australia Time - Broken Hill",
    value: "GMT+10:30",
    city: "Broken Hill",
  },
  {
    id: 320,
    label: "Eastern Australia Time - Macquarie",
    value: "GMT+11:00",
    city: "Macquarie",
  },
  {
    id: 321,
    label: "Magadan Standard Time - Magadan",
    value: "GMT+11:00",
    city: "Magadan",
  },
  {
    id: 322,
    label: "Sakhalin Standard Time - Sakhalin",
    value: "GMT+11:00",
    city: "Sakhalin",
  },
  {
    id: 323,
    label: "Srednekolymsk Time - Srednekolymsk",
    value: "GMT+11:00",
    city: "Srednekolymsk",
  },
  {
    id: 324,
    label: "Eastern Australia Time - Hobart",
    value: "GMT+11:00",
    city: "Hobart",
  },
  {
    id: 325,
    label: "Lord Howe Time - Lord Howe",
    value: "GMT+11:00",
    city: "Lord Howe",
  },
  {
    id: 326,
    label: "Eastern Australia Time - Melbourne",
    value: "GMT+11:00",
    city: "Melbourne",
  },
  {
    id: 327,
    label: "Eastern Australia Time - Sydney",
    value: "GMT+11:00",
    city: "Sydney",
  },
  {
    id: 328,
    label: "Bougainville Time - Bougainville",
    value: "GMT+11:00",
    city: "Bougainville",
  },
  {
    id: 329,
    label: "Vanuatu Standard Time - Efate",
    value: "GMT+11:00",
    city: "Efate",
  },
  {
    id: 330,
    label: "Solomon Islands Time - Guadalcanal",
    value: "GMT+11:00",
    city: "Guadalcanal",
  },
  {
    id: 331,
    label: "Kosrae Time - Kosrae",
    value: "GMT+11:00",
    city: "Kosrae",
  },
  {
    id: 332,
    label: "New Caledonia Standard Time - Noumea",
    value: "GMT+11:00",
    city: "Noumea",
  },
  {
    id: 333,
    label: "Ponape Time - Pohnpei",
    value: "GMT+11:00",
    city: "Pohnpei",
  },
  {
    id: 334,
    label: "Anadyr Standard Time - Anadyr",
    value: "GMT+12:00",
    city: "Anadyr",
  },
  {
    id: 335,
    label: "Petropavlovsk-Kamchatski Standard Time - Kamchatka",
    value: "GMT+12:00",
    city: "Kamchatski Standard Time",
  },
  {
    id: 336,
    label: "Fiji Standard Time - Fiji",
    value: "GMT+12:00",
    city: "Fiji",
  },
  {
    id: 337,
    label: "Tuvalu Time - Funafuti",
    value: "GMT+12:00",
    city: "Funafuti",
  },
  {
    id: 338,
    label: "Marshall Islands Time - Kwajalein",
    value: "GMT+12:00",
    city: "Kwajalein",
  },
  {
    id: 339,
    label: "Marshall Islands Time - Majuro",
    value: "GMT+12:00",
    city: "Majuro",
  },
  {
    id: 340,
    label: "Nauru Time - Nauru",
    value: "GMT+12:00",
    city: "Nauru",
  },
  {
    id: 341,
    label: "Norfolk Island Time - Norfolk",
    value: "GMT+12:00",
    city: "Norfolk",
  },
  {
    id: 342,
    label: "Gilbert Islands Time - Tarawa",
    value: "GMT+12:00",
    city: "Tarawa",
  },
  {
    id: 343,
    label: "Wake Island Time - Wake",
    value: "GMT+12:00",
    city: "Wake",
  },
  {
    id: 344,
    label: "Wallis & Futuna Time - Wallis",
    value: "GMT+12:00",
    city: "Wallis",
  },
  {
    id: 345,
    label: "Apia Standard Time - Apia",
    value: "GMT+13:00",
    city: "Apia",
  },
  {
    id: 346,
    label: "New Zealand Time - Auckland",
    value: "GMT+13:00",
    city: "Auckland",
  },
  {
    id: 347,
    label: "Tokelau Time - Fakaofo",
    value: "GMT+13:00",
    city: "Fakaofo",
  },
  {
    id: 348,
    label: "Phoenix Islands Time - Enderbury",
    value: "GMT+13:00",
    city: "Enderbury",
  },
  {
    id: 349,
    label: "Tonga Standard Time - Tongatapu",
    value: "GMT+13:00",
    city: "Tongatapu",
  },
  {
    id: 350,
    label: "Chatham Time - Chatham",
    value: "GMT+13:45",
    city: "Chatham",
  },
  {
    id: 351,
    label: "Line Islands Time - Kiritimati",
    value: "GMT+14:00",
    city: "Kiritimati",
  },
];
